// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asbdvmhhncgrwmcqxydf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzYmR2bWhobmNncndtY3F4eWRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzYwNjUsImV4cCI6MjA2OTY1MjA2NX0.sgbFMSOiHWNXpFccuPIYJQuNux9M8p4Y9VsCgtlBXto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});